valid_chars={'A': 'N', 
             'B': 'O', 
             'C': 'P', 
             'D': 'Q',
             'E': 'R',
             'F': 'S',
             'G': 'T',
             'H': 'U',
             'I': 'V',
             'J': 'W',
             'K': 'X',
             'L': 'Y',
             'M': 'Z',
             'N': 'A',
             'O': 'B' ,
             'P': 'C' ,
             'Q': 'D' ,
             'R': 'E' ,
             'S': 'F' ,
             'T': 'G' ,
             'U': 'H' ,
             'V': 'I' ,
             'W': 'J' ,
             'X': 'K' ,
             'Y': 'L' ,
             'Z': 'M' ,
             'a': 'n',
             'b': 'o',
             'c': 'p',
             'd': 'q',
             'e': 'r',
             'f': 's',
             'g': 't',
             'h': 'u',
             'i': 'v',
             'j': 'w',
             'k': 'x',
             'l': 'y',
             'm': 'z',
             'n': 'a',
             'o': 'b',
             'p': 'c',
             'q': 'd',
             'r': 'e',
             's': 'f',
             't': 'g',
             'u': 'h',
             'v': 'i',
             'w': 'j',
             'x': 'k',
             'y': 'l',
             'z': 'm',
             }
forbidden=[' ','0','1','2','3','4','5','6','7','8','9']
s=list(input())
for i in range(len(s)): 
    if s[i] in forbidden: continue
    s[i]=valid_chars[s[i]]
s=''.join(s)
print(s)