n=int(input())
for _ in range(n): print("@"*n,end=''); print(" "*3*n,end=''); print("@"*n)
for _ in range(n): print("@"*n,end=''); print(" "*2*n,end=''); print("@"*n)
for _ in range(n): print("@@@"*n)
for _ in range(n): print("@"*n,end=''); print(" "*2*n,end=''); print("@"*n)
for _ in range(n): print("@"*n,end=''); print(" "*3*n,end=''); print("@"*n)